"""
Recommendation output DTOs.

These models represent the structured output produced by the recommendation
engine and returned to the caller via the API or UI.

Hierarchy
---------
``RecommendationResponse``
    └── summary          : str | None
    └── recommendations  : list[Recommendation]
        └── restaurant   : Restaurant  (full metadata)
        └── rank         : int
        └── explanation  : str
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from src.models.restaurant import Restaurant


class Recommendation(BaseModel):
    """A single ranked restaurant recommendation.

    Produced by the recommendation engine after merging LLM output with
    full restaurant metadata from the repository.

    Attributes
    ----------
    restaurant:
        Complete ``Restaurant`` record with all metadata fields.
    rank:
        1-based position in the ordered result list.
    explanation:
        Human-readable rationale for why this restaurant was recommended,
        generated by the LLM or (on fallback) constructed from rating/cuisine data.
    """

    model_config = ConfigDict(frozen=True)

    restaurant: Restaurant = Field(
        description="Full restaurant record with all metadata.",
    )
    rank: int = Field(
        ge=1,
        description="1-based rank within the result set.",
    )
    explanation: str = Field(
        description="Reason this restaurant was recommended.",
    )


class RecommendationResponse(BaseModel):
    """Top-level response returned by the recommendation endpoint.

    Attributes
    ----------
    summary:
        Optional high-level AI-generated summary of the result set.
        ``None`` when the LLM is unavailable and the fallback ranker is used.
    recommendations:
        Ordered list of ``Recommendation`` objects (rank 1 = best match).
    source:
        Indicates whether recommendations were produced by the LLM or the
        rule-based fallback ranker.
    """

    model_config = ConfigDict(frozen=True)

    summary: str | None = Field(
        default=None,
        description="AI-generated summary of the recommendations, if available.",
    )
    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description="Ordered list of recommendations (best match first).",
    )
    source: str = Field(
        default="llm",
        description="'llm' if powered by the language model, 'fallback' otherwise.",
    )
